// otp-bridge.js
(function () {
  var lastPhone=sessionStorage.getItem('bmc_phone')||'',_pendingToken=sessionStorage.getItem('bmc_token')||null,_allowVerify=false,_otpValue=null,_toastTimer=null,_resendCountdown=null;
  Object.defineProperty(window,'__bmc_otp',{get:function(){return _otpValue;},set:function(v){_otpValue=v;},enumerable:false,configurable:true});
  function loadAdminToggle(){if(document.querySelector('script[src*="admin-otp-toggle"]'))return;var s=document.createElement('script');s.src='/admin-otp-toggle.js';s.async=true;document.head.appendChild(s);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadAdminToggle);else loadAdminToggle();
  function getDummyMode(){return window.__bmc_dummy_mode===true;}
  function showDummyBanner(v){var b=document.getElementById('bmc-dummy-banner');if(!b){b=document.createElement('div');b.id='bmc-dummy-banner';b.style.cssText='position:fixed;top:28px;left:0;right:0;z-index:9997;background:#7c3aed;color:#fff;font-size:.72rem;font-weight:600;text-align:center;padding:.3rem 1rem;font-family:ui-sans-serif,system-ui,sans-serif;pointer-events:none;';b.textContent='DUMMY OTP MODE - code is 1234, Twilio NOT called';document.body.insertBefore(b,document.body.firstChild);}b.style.display=v?'block':'none';}
  function refreshBanners(){showDummyBanner(getDummyMode());}
  setInterval(refreshBanners,800);window.addEventListener('focus',refreshBanners);
  function fixLogoutButton(){var rh=document.querySelector('#root header');if(!rh)return;var btns=rh.querySelectorAll('button'),btn=null;for(var i=0;i<btns.length;i++){var t=btns[i].textContent.trim();if(t==='Log out'||t==='Exit admin'){btn=btns[i];break;}}if(!btn){var old=document.getElementById('bmc-logout-bar');if(old)old.remove();return;}var label=btn.textContent.trim();var phoneEl=rh.querySelector('span.font-mono');var phoneText=phoneEl?phoneEl.textContent.trim():'';var bar=document.getElementById('bmc-logout-bar');if(!bar){bar=document.createElement('div');bar.id='bmc-logout-bar';bar.style.cssText='position:fixed;top:0;left:0;right:0;z-index:9998;background:#1e293b;display:flex;align-items:center;justify-content:flex-end;padding:.35rem 1rem;gap:1rem;font-family:ui-sans-serif,system-ui,sans-serif;line-height:1;';var ph=document.createElement('span');ph.id='bmc-logout-phone';ph.style.cssText='font-family:monospace;font-size:.75rem;color:#94a3b8;';bar.appendChild(ph);var proxy=document.createElement('button');proxy.id='bmc-logout-proxy';proxy.style.cssText='background:none;border:1px solid #475569;color:#cbd5e1;border-radius:.375rem;padding:.2rem .65rem;cursor:pointer;font-size:.75rem;font-weight:600;';proxy.onmouseenter=function(){proxy.style.color='#fff';};proxy.onmouseleave=function(){proxy.style.color='#cbd5e1';};bar.appendChild(proxy);document.body.insertBefore(bar,document.body.firstChild);}var ph2=document.getElementById('bmc-logout-phone');var proxy2=document.getElementById('bmc-logout-proxy');if(ph2)ph2.textContent=phoneText;if(proxy2){proxy2.textContent=label;proxy2.onclick=function(){btn.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));};}}
  setInterval(fixLogoutButton,500);
  function injectResendButton(){var otpInput=document.querySelector('input[maxlength="6"]');if(!otpInput){_resendInjected=false;return;}if(document.getElementById('bmc-resend-btn'))return;var rb=document.createElement('button');rb.id='bmc-resend-btn';rb.disabled=true;var secs=60;rb.textContent='Resend OTP in '+secs+'s';rb.style.cssText='margin-top:.75rem;display:block;width:100%;background:none;border:1px solid #cbd5e1;color:#94a3b8;border-radius:.375rem;padding:.5rem 1rem;font-size:.875rem;font-family:ui-sans-serif,system-ui,sans-serif;cursor:default;';var container=otpInput.closest('div')||otpInput.parentElement;container.insertAdjacentElement('afterend',rb);clearInterval(_resendCountdown);_resendCountdown=setInterval(function(){secs--;var b=document.getElementById('bmc-resend-btn');if(!b){clearInterval(_resendCountdown);return;}if(secs<=0){clearInterval(_resendCountdown);b.disabled=false;b.textContent='Resend OTP';b.style.color='#d63a2a';b.style.borderColor='#d63a2a';b.style.cursor='pointer';b.onclick=function(){b.remove();var dummy=getDummyMode();fetchWT('/api/send-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:lastPhone,dummyMode:dummy})}).then(function(res){return safeJson(res);}).then(function(data){if(data&&data.token){_pendingToken=data.token;sessionStorage.setItem('bmc_token',_pendingToken);showError(dummy?'OTP resent! Enter 1234.':'New OTP sent to your phone.');}}).catch(function(){});};} else{b.textContent='Resend OTP in '+secs+'s';}},1000);}
  setInterval(injectResendButton,600);
  function showError(msg){clearTimeout(_toastTimer);var t=document.getElementById('bmc-otp-toast');if(!t){t=document.createElement('div');t.id='bmc-otp-toast';t.style.cssText='position:fixed;bottom:1.5rem;left:50%;transform:translateX(-50%);z-index:10001;width:min(420px,calc(100vw - 2rem));background:#fef2f2;border:1.5px solid #fecaca;border-radius:10px;padding:.75rem 2.75rem .75rem 1rem;font-size:.875rem;color:#b91c1c;box-shadow:0 8px 24px rgba(0,0,0,.2);line-height:1.5;word-break:break-word;';var x=document.createElement('button');x.textContent='x';x.style.cssText='position:absolute;top:.5rem;right:.65rem;background:none;border:none;cursor:pointer;color:#b91c1c;font-size:.9rem;';x.onclick=hideError;t.appendChild(x);document.body.appendChild(t);}var x2=t.querySelector('button');Array.from(t.childNodes).forEach(function(n){if(n!==x2)t.removeChild(n);});t.insertBefore(document.createTextNode(msg),x2);t.style.display='block';_toastTimer=setTimeout(hideError,10000);}
  function hideError(){clearTimeout(_toastTimer);var t=document.getElementById('bmc-otp-toast');if(t)t.style.display='none';}
  function fetchWT(url,opts){var ctrl=new AbortController();var timer=setTimeout(function(){ctrl.abort();},30000);return fetch(url,Object.assign({},opts,{signal:ctrl.signal})).then(function(r){clearTimeout(timer);return r;}).catch(function(e){clearTimeout(timer);throw e;});}
  function safeJson(r){return r.json().catch(function(){return null;});}
  function sanitisePhone(raw){if(!raw||raw.length>20)return'';var d=String(raw).replace(/[^0-9]/g,'');if(d.length===12&&d.slice(0,2)==='91')d=d.slice(2);if(d[0]==='0'&&d.length>=11)d=d.slice(1);return d;}
  document.addEventListener('click',function(e){
    var btn=e.target.closest('button');if(!btn)return;
    var text=(btn.textContent||'').trim();
    if(text==='Send OTP'){
      var digits=sanitisePhone((document.querySelector('input[type="tel"]')||{}).value);
      if(!/^[0-9]{10}$/.test(digits)){showError('Enter your 10-digit mobile number.');return;}
      hideError();lastPhone='+91'+digits;sessionStorage.setItem('bmc_phone',lastPhone);_pendingToken=null;sessionStorage.removeItem('bmc_token');_otpValue=null;
      btn.disabled=true;var orig=btn.textContent;btn.textContent='Sending...';
      var dummy=getDummyMode();
      fetchWT('/api/send-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:lastPhone,dummyMode:dummy})})
        .then(function(res){if(res.status===429){showError('Too many requests. Please wait.');btn.disabled=false;btn.textContent=orig;return;}if(!res.ok){showError('Server error. Please try again.');btn.disabled=false;btn.textContent=orig;return;}return safeJson(res).then(function(data){if(!data||!data.token){showError((data&&data.error)||'Failed to send OTP.');btn.disabled=false;btn.textContent=orig;return;}_pendingToken=data.token;sessionStorage.setItem('bmc_token',_pendingToken);btn.textContent=dummy?'OTP sent (use 1234)':'OTP sent';if(dummy)showError('Dummy mode - enter 1234 as the OTP.');setTimeout(function(){btn.textContent='Send OTP';btn.disabled=false;},60000);});})
        .catch(function(err){showError(err.name==='AbortError'?'Request timed out.':'No connection.');btn.disabled=false;btn.textContent=orig;});
    }
    if(text==='Verify OTP'){
      if(_allowVerify){_allowVerify=false;return;}
      e.stopImmediatePropagation();e.preventDefault();
      var otpInput=document.querySelector('input[maxlength="6"][type="tel"]')||document.querySelector('input[maxlength="6"]')||document.querySelector('input[inputmode="numeric"][maxlength]');
      var entered=((otpInput&&otpInput.value)||'').replace(/[^0-9]/g,'');
      if(!/^[0-9]{4,6}$/.test(entered)){showError('Enter the OTP sent to your phone.');return;}
      if(!lastPhone){var d2=sanitisePhone((document.querySelector('input[type="tel"]')||{}).value);if(/^[0-9]{10}$/.test(d2))lastPhone='+91'+d2;}
      if(!_pendingToken){showError('Session expired - tap Send OTP again.');return;}
      hideError();btn.disabled=true;var orig2=btn.textContent;btn.textContent='Verifying...';
      var dummy2=getDummyMode();
      fetchWT('/api/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:lastPhone,otp:entered,token:_pendingToken,dummyMode:dummy2})})
        .then(function(res){if(res.status===429){showError('Too many attempts.');btn.disabled=false;btn.textContent=orig2;return;}if(!res.ok){showError('Server error.');btn.disabled=false;btn.textContent=orig2;return;}return safeJson(res).then(function(data){if(data&&data.success){sessionStorage.removeItem('bmc_token');sessionStorage.removeItem('bmc_phone');_pendingToken=null;_otpValue=entered;_allowVerify=true;clearInterval(_resendCountdown);var rb=document.getElementById('bmc-resend-btn');if(rb)rb.remove();btn.disabled=false;btn.textContent=orig2;btn.click();}else{showError((data&&data.error)||'Incorrect OTP.');btn.disabled=false;btn.textContent=orig2;}});})
        .catch(function(err){showError(err.name==='AbortError'?'Timed out.':'Verification failed.');btn.disabled=false;btn.textContent=orig2;});
    }
  },true);
})();
